# Generated by Django 5.1.1 on 2024-09-15 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
